services:
  electric:
    image: electricsql/electric:latest
    container_name: electric_dev_sync
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ELECTRIC_SECRET: ${ELECTRIC_SECRET}
      ELECTRIC_USAGE_REPORTING: false
    ports:
      - 30000:3000
    volumes:
      - electric_data:/var/lib/electric/persistent

volumes:
  electric_data:
